version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
  build:
    commands:
      - echo Build started on `date`
      - export BUCKET=testdockertest
      - mvn package shade:shade
      - mkdir artifcts
      - cp target/Docker-Service-0.0.1-SNAPSHOT.jar artifcts/
      - cd artifcts
      - ls -ltr
      - unzip docker-Service-0.0.1-SNAPSHOT.jar
      - rm artifcts/Docker-Service-0.0.1-SNAPSHOT.jar
      - rm -rf tst src buildspec.yml pom.xml
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml 
  post_build:
    commands:
      - echo Build completed on `date` !!!     
artifacts:
  files:
    - target/Docker-Service-0.0.1-SNAPSHOT.jar
    - samTemplate.yaml
    - outputtemplate.yaml




