AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
 Name:
  Description: Bucket Name
  Type: String
  Default: mybucket 
 ObjectKey:
  Description: Bucket Key
  Type: String
  Default: Mybucketkey 
  
Globals:
  Environment:
   Variables:
    Bucket_Name: !Ref Name
    key : !Ref ObjectKey
    

Resources:
  CreateScheduler :
    Type: AWS::Serverless::Function
    Properties:
       Handler: com.docker.lambda.LambdaHandler::handleRequest
       Role: arn:aws:iam::977559110223:role/service-role/MyLambda
       Runtime: java8
       Timeout: 900
       CodeUri: ./    
       Events:
        CheckWebsiteScheduledEvent:
         Type: Schedule
         Properties:
          Schedule: rate(1 minute)
  CreateApi :
    Type: AWS::Serverless::Function
    Properties:
       Handler: com.docker.lambda.LambdaAPIHandler::handleRequest
       Role: arn:aws:iam::977559110223:role/service-role/MyLambda
       Runtime: java8
       Timeout: 900
       CodeUri: ./    
       Events:
        GetEvent:
         Type: Api
         Properties:
          Path: /
          Method: GET
          
     









