AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CheckWebsitePeriodically:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.docker.lambda.LambdaHandler::handleRequest
      Runtime: JAVA8
      Timeout: 900
      CodeUri: ./
      Events:
       CheckWebsiteScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
       GetEvent:
          Type: Api
          Properties:
            Path: /client
            Method: GET
       Environment:
       Variables :
        REGION:ap-southeast-2   










