AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CheckWebsitePeriodically:
   Type: AWS::Serverless::Function
  CreateScheduler :
    Handler: com.docker.lambda.LambdaHandler::handleRequest
    Events:
     CheckWebsiteScheduledEvent:
      Type: Schedule
      Properties:
       Schedule: rate(1 minute)
       Runtime: JAVA8
       Timeout: 900
       CodeUri: ./     
  CreateApi :
    Handler: com.docker.lambda.LambdaAPIHandler::handleRequest
    Events:
     GetEvent:
      Type: Api
      Properties:
        Path: /
        Method: GET
        Runtime: JAVA8
        Timeout: 900
        CodeUri: ./  
     Environment:
       Variables :
         REGION:ap-southeast-2   










